# Generated by Django 5.1.5 on 2025-02-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
