# Generated by Django 5.1.5 on 2025-03-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbapi', '0002_shipment_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
